#!/usr/bin/env python3
"""Build the single deployable stylesheet from ordered authored modules."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "css" / "src"
OUTPUT = ROOT / "css" / "site.css"

# The source list is the architectural boundary. Every source declares its
# cascade layer; this order remains readable and deterministic in the generated
# artifact without relying on late "correction" files.
SOURCES = (
    "foundations/reset.css",
    "foundations/tokens.css",
    "foundations/base.css",
    "foundations/typography.css",
    "layout/containers.css",
    "layout/grid.css",
    "layout/sections.css",
    "layout/responsive.css",
    "components/top-bar.css",
    "components/header.css",
    "components/mobile-menu.css",
    "components/footer.css",
    "components/buttons.css",
    "components/system-primitives.css",
    "components/breadcrumbs.css",
    "components/cards.css",
    "components/franciele-cutouts.css",
    "components/forms.css",
    "components/disclosures.css",
    "components/directories.css",
    "components/cookie-banner.css",
    "components/floating-tools.css",
    "compositions/heroes.css",
    "compositions/media-sections.css",
    "compositions/art-sections.css",
    "compositions/statements.css",
    "compositions/directory-sections.css",
    "pages/families.css",
    "pages/home.css",
    "pages/home-art-direction.css",
    "pages/about.css",
    "pages/mission.css",
    "pages/values.css",
    "pages/treatments.css",
    "pages/care.css",
    "pages/skin.css",
    "pages/laser.css",
    "pages/results.css",
    "pages/testimonials.css",
    "pages/journal.css",
    "pages/blog.css",
    "pages/faq.css",
    "pages/consultation.css",
    "pages/contact.css",
    "pages/policies.css",
    "pages/accessibility.css",
    "pages/utilities.css",
    "pages/sitewide-art-direction.css",
    "pages/backgrounds.css",
    "pages/hero-system.css",
    "pages/editorial-typography.css",
    "pages/body-scenes.css",
    "pages/site-backgrounds.css",
    "utilities/accessibility.css",
)


def build_output() -> str:
    missing = [name for name in SOURCES if not (SOURCE_ROOT / name).is_file()]
    if missing:
        raise SystemExit(f"Missing CSS sources: {', '.join(missing)}")
    chunks = [
        "/* Generated by scripts/build-css.py. Edit css/src/, not this file. */\n"
        "@layer reset, tokens, base, layout, components, compositions, pages, utilities;\n"
    ]
    for name in SOURCES:
        content = (SOURCE_ROOT / name).read_text(encoding="utf-8").rstrip()
        chunks.append(f"\n/* Source: css/src/{name} */\n{content}\n")
    return "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when css/site.css is missing or stale without writing it.",
    )
    args = parser.parse_args()
    output = build_output()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != output:
            print("css/site.css is stale; run python3 scripts/build-css.py")
            return 1
        print(f"CSS build is current ({len(SOURCES)} modules, {len(output):,} bytes).")
        return 0
    OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"Built {OUTPUT.relative_to(ROOT)} from {len(SOURCES)} modules ({len(output):,} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
